apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment 
  labels:
    app: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs 
        image: anandtechy/nodejswebapp:latest 
        ports:
        - containerPort: 3000
