apiVersion: v1
kind: Service
metadata:
  name: nodejsmyapp-service
spec:
  selector:
    app: anandtechy/nodejswebapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
